### ISSUE TITLE
OkHttp3 NoSuchMethodError when running requestOrder()

### ISSUE THREAD

**Issue by fear025** [Petersoj/alpaca-java#102]
When testing a buy request against my Alpaca Paper account, I'm executing this method:
```
Order requestOrder(String symbol, Double quantity, Double notional, OrderSide side, OrderType type,
            OrderTimeInForce timeInForce, Double limitPrice, Double stopPrice, Double trailPrice, Double trailPercent,
            Boolean extendedHours, String clientOrderId, OrderClass orderClass, Double takeProfitLimitPrice,
            Double stopLossStopPrice, Double stopLossLimitPrice)
```

And I get this error:
```
Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
	at net.jacobpeterson.alpaca.util.okhttp.JSONBodyBuilder.build(JSONBodyBuilder.java:61)
	at net.jacobpeterson.alpaca.rest.endpoint.OrdersEndpoint.requestOrder(OrdersEndpoint.java:209)
```

After investigating a little, I discovered that if I change around the parameter values in JSONBodyBuilder to the following, then everything works fine, and I am able to place buy and sell orders.
```
    public RequestBody build() {
        return RequestBody.create(JSON_MEDIA_TYPE, bodyJSON != null ? bodyJSON : bodyJsonObject.toString());
    }
```

The biggest problem with this fix is that this particular create() method is marked as deprecated.

I've tried this by inserting the maven dependency directly in my eclipse project, and by using the eclipse gradle tools to run the clean and build gradle actions on a copy that I've downloaded with git, and both give me that same error.

It's certainly possible that I've got some other configuration issue that's causing this problem, and I'm definitely confused about how to use RequestBody.create() as it doesn't even seem to be listed anywhere in the OkHttp3 4.x API documentation.

Finally, I am using the Oracle jdk-11.0.2.

**Comment by Petersoj** [comment]
Hmm, I'm not sure exactly what is happening on your end, but it could be that a different version of OkHttp is on your classpath than version `4.9.1` which is the version `alpaca-java` uses. But anyway, according the source of `RequestBody` [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/RequestBody.kt), the method signature that has the request body content string first and then the `MediaType` second doesn't even exist, so perhaps the `4.9.1` version in Maven Central doesn't reflect that yet. Either that, or I'm missing something...
FYI, the `@JvmName("create")` on the Kotlin method signatures in that class file is what defines the method names for Java in this case.
I tested `requestMarketOrder` using the deprecated `RequestBody.create()` method as well and it works the same as non-deprecated method. So for now, I would recommend installing your patched version to your local maven repo and using that instead since the Maven Central one is not working for your current project configuration. I'll keep this issue open until I have the time to do some more digging here. Thanks for reporting this :)

**Comment by Petersoj** [comment]
Looking in to this further, it appears that the method call being used in `JSONBodyBuilder` (with the content `String` first and the `MediaType` second) is the correct usage. [This](https://github.com/square/okhttp/issues/6309#issuecomment-704914951) issue comment explains it a bit, but you can see all the detail of what happened in [this](https://github.com/square/okhttp/commit/8bb58332dbacdd2bb9beb8e5c813f22508ebeb27) commit. If you take a look at [`RequestBody.kt`](https://github.com/square/okhttp/commit/8bb58332dbacdd2bb9beb8e5c813f22508ebeb27#diff-ab573759adaad4f83ee49ed90b3bf8257c8fcfbfa186d4bccc058553aed7a541R165-R213) you can see the author added a few methods for Java-specific API usage that enables the use of some Kotlin extension functions. Also within that commit, you can see all the Java unit tests that were modified to strictly use the method signature with the content `String` first and the `MediaType` second. So your issue is likely a project configuration issue (e.g. different version of `OkHttp` on the classpath) or something else. Let me know if that helps.

**Comment by fear025** [comment]
Thanks for looking into this more! The problem was definitely a different version on my classpath.

For reference, if anyone else has this problem, I was able to figure out exactly where this was coming from by using the following code:
```
    	ClassLoader classLoader = RequestBody.class.getClassLoader();

    	java.net.URL resource = classLoader.getResource("okhttp3/RequestBody.class");
    	System.out.println(resource);
```

It turns out I had another project included which used a backlevel version of the okhttp library, and it was getting picked up first in the classpath.

It was especially confusing because the backlevel version was being found first even when I explicitly included the most recent version in my maven pom.xml file.
