### ISSUE TITLE
Version 9.0.0 release seems to have dropped support for BarMessage.getVolume()

### ISSUE THREAD

**Issue by Kurru** [Petersoj/alpaca-java#113]
Version 9.0.0 release seems to have dropped support for `BarMessage.getVolume()`. At least, the method `getVolume()` seems to be absent. 

Was this intentional? 

`net.jacobpeterson.alpaca.model.endpoint.marketdata.common.realtime.bar.BarMessage.getVolume()`

**Comment by Kurru** [comment]
Oh, I found `net.jacobpeterson.alpaca.model.endpoint.marketdata.stock.realtime.bar.StockBarMessage` in the json_schema which does contain the `volume` field.

Thanks for the update/sorry about the noise!

**Comment by Petersoj** [comment]
Hey @Kurru, no worries. The crypto and stock market data APIs share a lot of common fields (e.g. open, close, trade ID, etc...), but the `volume` field in crypto is a floating point number and the `volume` field in stock data is an `int` (among other differences) so I made this distinction via `CryptoBarMessage` and `StockBarMessage`. This way, a user can use the common fields between crypto and stocks with the `BarMessage` object instead of having those API endpoints use completely different object models.
