### ISSUE TITLE
alpaca-java's log4j2.properties file is rendering my local config unusable

### ISSUE THREAD

**Issue by jessethouin** [Petersoj/alpaca-java#74]
I know how to work around it, but I should not have to when using a 3rd party library. Please remove log configs from your library.

**Comment by jessethouin** [comment]
I should specify this is from the maven import. I should also specify that I'm very thankful for for this library!! Keep up the great work. :)

**Comment by Petersoj** [comment]
Thanks for reporting this. A lot of 3rd party libraries use Log4j properties and it's usually the responsibility of the library user to set their logging configuration to their liking. Use [this](https://stackoverflow.com/a/1140498/4352701) guide to specify the Log4j properties file for your environment.
I'll look in to changing how this library sets the configuration for Log4j so that it's easier for the library user.

**Comment by Petersoj** [comment]
Closing this as there is a solution available. Let me know if you have problems :)

**Comment by Petersoj** [comment]
Following up on this: I have found that using Log4j dependency with the `compile` closure in Gradle will cause Log4j to be included on the classpath for library users unless the library user explicitly excludes the Log4j group and artifact ID. I will be changing all the dependencies from `compile` to `implementation` which shields library users from direct access to `compile` dependencies that this library uses from their application. So I think it only puts the dependency on classpath at the user-level and not at the library-level. I'll be changing the logging library from Log4j (which is an SLF4j implementation) to SLF4j anyway so you won't even see a `log4j.properties` file on the classpath from the Maven Central artifact. Hopefully that clears things up!
