### ISSUE TITLE
AlpacaAPI.getBars 7.0

### ISSUE THREAD

**Issue by bdavid** [Petersoj/alpaca-java#92]
Hello. I'm upgrading from version 6.1 to version 7.0 and for some reason I keep getting zero results when I call AlpacaAPI.getBars().

val symbol = "QQQ";
val alpaca = new AlpacaAPI();
val start = ZonedDateTime.of(2021, 3, 16, 9, 30, 0, 0, ZoneId.of("America/New_York"));
val end = ZonedDateTime.of(2021, 3, 16, 16, 0, 0, 0, ZoneId.of("America/New_York"));
val map = alpaca.getBars(symbol, start, end, null, null, BarsTimeFrame.MINUTE);
val bars = map.getBars();
System.out.println(bars.size()); // prints 0

I tried various inputs but no luck. Any ideas?

**Comment by Petersoj** [comment]
Alpaca is currently backfilling the Bars v2 API right now so that endpoint won't return anything until they have finished the backfill. You can see the status of the backfill and the currently available endpoint data [here](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/#public-beta-status). I would recommend staying on `6.1` until they finish backfilling the v2 endpoints (which should be soon hopefully).

**Comment by bdavid** [comment]
Got it. Thanks for quick reply and all your work on the Alpaca SDK!
